"""
Data models for the trading system.

Defines all core types: Signal, Order, Trade, Position, Events, etc.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum

# ── Enums ──────────────────────────────────────────────────────

class SignalAction(Enum):
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


class Side(Enum):
    BUY = "buy"
    SELL = "sell"


class OrderType(Enum):
    MARKET = "market"
    LIMIT = "limit"


class OrderStatus(Enum):
    PENDING = "pending"
    SUBMITTED = "submitted"
    FILLED = "filled"
    PARTIALLY_FILLED = "partially_filled"
    CANCELLED = "cancelled"
    REJECTED = "rejected"


class TradeOutcome(Enum):
    WIN = "win"
    LOSS = "loss"
    BREAKEVEN = "breakeven"
    OPEN = "open"


class MarketRegime(Enum):
    TRENDING_UP = "trending_up"
    TRENDING_DOWN = "trending_down"
    MEAN_REVERTING = "mean_reverting"
    HIGH_VOLATILITY = "high_volatility"
    LOW_VOLATILITY = "low_volatility"


class DecisionStatus(Enum):
    """Final verdict for a trade decision memo (seb.ai-style funnel)."""
    APPROVED = "approved"     # passes every gate — eligible to trade
    WATCHLIST = "watchlist"   # interesting but a soft gate failed — watch, don't act
    REJECTED = "rejected"     # blocked by risk rules — do not trade


class EventType(Enum):
    SIGNAL_GENERATED = "signal_generated"
    RISK_APPROVED = "risk_approved"
    RISK_REJECTED = "risk_rejected"
    ORDER_SUBMITTED = "order_submitted"
    ORDER_FILLED = "order_filled"
    ORDER_REJECTED = "order_rejected"
    ORDER_CANCELLED = "order_cancelled"
    STOP_LOSS_HIT = "stop_loss_hit"
    TAKE_PROFIT_HIT = "take_profit_hit"
    CIRCUIT_BREAKER = "circuit_breaker"
    MARKET_OPEN = "market_open"
    MARKET_CLOSE = "market_close"


# ── Data Classes ───────────────────────────────────────────────

@dataclass
class Signal:
    """A trading signal generated by a strategy."""
    symbol: str
    action: SignalAction
    strategy: str
    confidence: float  # 0.0 to 1.0
    entry_price: float | None = None
    stop_loss: float | None = None
    take_profit: float | None = None
    reasoning: dict = field(default_factory=dict)
    regime: MarketRegime | None = None
    id: str = field(default_factory=lambda: uuid.uuid4().hex[:8])
    timestamp: datetime = field(default_factory=datetime.utcnow)


@dataclass
class Order:
    """An order to be submitted to the broker."""
    symbol: str
    side: Side
    quantity: float
    order_type: OrderType = OrderType.MARKET
    limit_price: float | None = None
    status: OrderStatus = OrderStatus.PENDING
    broker_order_id: str | None = None
    signal_id: str | None = None
    id: str = field(default_factory=lambda: uuid.uuid4().hex[:8])
    created_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class Position:
    """An open position."""
    symbol: str
    side: Side
    quantity: float
    entry_price: float
    entry_time: datetime
    current_price: float = 0.0
    unrealized_pnl: float = 0.0
    unrealized_pnl_pct: float = 0.0
    market_value: float = 0.0

    def __post_init__(self):
        if self.current_price and self.entry_price:
            self.unrealized_pnl = (self.current_price - self.entry_price) * self.quantity
            if self.entry_price > 0:
                self.unrealized_pnl_pct = (self.current_price - self.entry_price) / self.entry_price
            self.market_value = self.current_price * self.quantity


@dataclass
class Trade:
    """A completed or open trade."""
    symbol: str
    side: Side
    strategy: str | None = None
    entry_time: datetime | None = None
    entry_price: float = 0.0
    quantity: float = 0.0
    exit_time: datetime | None = None
    exit_price: float = 0.0
    exit_reason: str | None = None
    pnl: float = 0.0
    pnl_pct: float = 0.0
    commission: float = 0.0
    outcome: TradeOutcome = TradeOutcome.OPEN
    signal_id: str | None = None
    entry_reasoning: dict = field(default_factory=dict)
    exit_reasoning: dict = field(default_factory=dict)
    id: str = field(default_factory=lambda: uuid.uuid4().hex[:8])

    def close(self, exit_price: float, exit_time: datetime, exit_reason: str = "signal"):
        """Close the trade and calculate P&L."""
        self.exit_price = exit_price
        self.exit_time = exit_time
        self.exit_reason = exit_reason

        if self.side == Side.BUY:
            self.pnl = (exit_price - self.entry_price) * self.quantity - self.commission
        else:
            self.pnl = (self.entry_price - exit_price) * self.quantity - self.commission

        if self.entry_price > 0:
            self.pnl_pct = self.pnl / (self.entry_price * self.quantity)

        if self.pnl > 0.001:
            self.outcome = TradeOutcome.WIN
        elif self.pnl < -0.001:
            self.outcome = TradeOutcome.LOSS
        else:
            self.outcome = TradeOutcome.BREAKEVEN


@dataclass
class Event:
    """An event in the system event bus."""
    type: EventType
    data: dict = field(default_factory=dict)
    source: str = ""
    timestamp: datetime = field(default_factory=datetime.utcnow)
    id: str = field(default_factory=lambda: uuid.uuid4().hex[:8])


@dataclass
class DecisionMemo:
    """
    A structured, human-readable trade decision — inspired by the seb.ai
    workflow's "Final Decision Memo". Every actionable signal produces one,
    whether or not it is traded, forming an audit trail.
    """
    symbol: str
    action: SignalAction
    status: DecisionStatus
    strategy: str
    signal_strength: float                 # 0..1 (from ensemble confidence)
    risk_level: str = "unknown"            # low | medium | high
    # Trade plan
    entry: float | None = None
    target: float | None = None
    stop: float | None = None
    invalidation: float | None = None   # level that proves the setup wrong
    timeframe: str = "1Day"
    risk_reward: float | None = None
    # Sizing (filled when risk approves)
    quantity: float = 0.0
    dollar_risk: float = 0.0
    # Context
    regime: MarketRegime | None = None
    rationale: str = ""                    # one-line reason for the setup
    reasons: list = field(default_factory=list)  # why this status was assigned
    signal_id: str | None = None
    id: str = field(default_factory=lambda: uuid.uuid4().hex[:8])
    timestamp: datetime = field(default_factory=datetime.utcnow)

    def render(self) -> str:
        """Render a plain-text decision memo."""
        def money(v):
            return f"${v:,.2f}" if isinstance(v, (int, float)) else "—"

        lines = [
            f"DECISION MEMO — {self.symbol} [{self.status.value.upper()}]",
            f"  Action:          {self.action.value.upper()} ({self.strategy})",
            f"  Signal strength: {self.signal_strength:.0%}",
            f"  Risk level:      {self.risk_level}",
            f"  Regime:          {self.regime.value if self.regime else '—'}",
            "  Trade plan:",
            f"    Entry:         {money(self.entry)}",
            f"    Target:        {money(self.target)}",
            f"    Stop:          {money(self.stop)}",
            f"    Invalidation:  {money(self.invalidation)}",
            f"    Timeframe:     {self.timeframe}",
            f"    Risk:Reward:   {self.risk_reward:.2f}" if self.risk_reward else "    Risk:Reward:   —",
        ]
        if self.quantity:
            lines.append(f"    Size:          {self.quantity:.4f} sh  (risk {money(self.dollar_risk)})")
        if self.rationale:
            lines.append(f"  Reason:          {self.rationale}")
        if self.reasons:
            lines.append(f"  Verdict basis:   {'; '.join(self.reasons)}")
        lines.append("  >> PAPER ONLY — human review required <<")
        return "\n".join(lines)
